/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaTutorial;

import com.formdev.flatlaf.FlatDarkLaf;
import javaTutorial.comboBox.ComboBox;
import javaTutorial.fibonacci.FibonacciGenerator;
import javaTutorial.names.NameGenerator;
import net.miginfocom.swing.MigLayout;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;

public class App extends JFrame {
    public static void main(String[] args) {
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (UnsupportedLookAndFeelException e) {
            throw new RuntimeException(e);
        }
        App app = new App();
        app.setVisible(true);
    }

    public App() {
        setTitle("Test Application");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(1000, 500);
        setLocationRelativeTo(null);
        setJMenuBar(createMenuBar());
        JPanel mainPanel = createMainPanel();
        add(mainPanel, BorderLayout.CENTER);
        setVisible(true);
    }

    private JMenuBar createMenuBar() {
        JMenuBar menuBar = new JMenuBar();

        JMenu fileMenu = new JMenu("File");
        fileMenu.setMnemonic(KeyEvent.VK_F);

        JMenuItem fileItem = new JMenuItem("Exit");
        fileItem.setMnemonic(KeyEvent.VK_X);
        fileItem.addActionListener(e->System.exit(0));
        fileMenu.add(fileItem);

        menuBar.add(fileMenu);
        return menuBar;
    }

    private JPanel createMainPanel() {
        JPanel panel = new JPanel();
        panel.setLayout(new MigLayout());

        JButton comboBoxBtn = new JButton("ComboBox");
        comboBoxBtn.addActionListener(e->new ComboBox());
        panel.add(comboBoxBtn);

        JButton nameGeneratorBtn = new JButton("Name Generator");
        nameGeneratorBtn.addActionListener(e->new NameGenerator());
        panel.add(nameGeneratorBtn, "wrap");

        JButton fibonacciBtn = new JButton("Fibonacci Sequence");
        fibonacciBtn.addActionListener(e->new FibonacciGenerator());
        panel.add(fibonacciBtn, "span");

        return panel;
    }
}
